Lesson 5
evg-tray/tn pull request #2
Opened 2016-11-14 19:20 UTC by evg-tray

2016-11-15 10:39 UTC, psylone requested changes

2016-11-15 10:39 UTC, psylone commented on Lesson3/models/wagon.rb
> +    @train.nil? && self.class.to_s == type
Можно передавать сам класс. Тогда вторая часть условия будет: `self.class == type`.

2016-11-15 10:39 UTC, psylone commented on Lesson3/models/train.rb
> +    trains = @@trains.select { |train| train.number == number }
Есть метод `detect`.

2016-11-15 10:39 UTC, psylone commented on Lesson3/models/train.rb
> +    @@trains << self
У меня 2 поезда: один пассажирский, другой товарный. Оба имеют одинаковый номер. Как поведёт себя метод `Train.find`?

2016-11-15 10:47 UTC, psylone requested changes

2016-11-15 10:47 UTC, psylone commented on Lesson3/modules/instance_counter.rb
> +    base.send :include, InstanceMethods
Можно сразу вызывать метод подключения модуля: `base.include InstanceMethods`.

2016-11-15 10:47 UTC, psylone commented on Lesson3/modules/instance_counter.rb
> +    def register_instance
Будет чуть лучше читаться если назвать метод: `register_instance!` (с `!` на конце).

2016-11-15 10:47 UTC, psylone commented on Lesson3/modules/instance_counter.rb
> +    :instances=
Вот это вот работает: `Train.instances = 21`.

2016-11-15 10:50 UTC, evg-tray commented on Lesson3/models/wagon.rb
> +    @train.nil? && self.class.to_s == type
`CONST = ClassName` ругается на неинициализированную константу

2016-11-15 11:01 UTC, evg-tray commented on Lesson3/models/train.rb
> +    @@trains << self
Думал над этим моментом, тут может быть и два товарных с одинаковым номером. Можно запретить создание нового объекта поезда если номер уже есть из класса поезд в методе initialize(такое же возможно в руби?), либо в самой логике программы это ограничивать. Пока же возвращает первый созданный поезд с таким номером.

2016-11-15 11:02 UTC, evg-tray commented on Lesson3/modules/instance_counter.rb
> +    base.send :include, InstanceMethods
В скринкасте говорилось, что include приватный и недоступен здесь.

2016-11-15 11:41 UTC, evg-tray commented on Lesson3/modules/instance_counter.rb
> +    :instances=
Думал, что разобрался с видимостью, оказалось далеко нет) Вот так прячет:
```ruby
module ClassMethods
    attr_reader :instances
    private
    attr_writer :instances
  end

  module InstanceMethods
    protected
    def register_instance!
      self.class.send :instances=, (self.class.instances || 0) + 1
    end
  end
```

2016-11-15 11:45 UTC, evg-tray commented on Lesson3/modules/instance_counter.rb
> +    :instances=
И вот так прячет:

``` ruby
module ClassMethods
  attr_accessor :instances
  private :instances=
end
```

Снова в голове путаница

2016-11-15 23:06 UTC, psylone commented on Lesson3/models/wagon.rb
> +    @train.nil? && self.class.to_s == type
А где такое, у нас же сравнение вместо присваивания?

2016-11-15 23:08 UTC, psylone commented on Lesson3/modules/instance_counter.rb
> +    base.send :include, InstanceMethods
Честно говоря, я обычно инстанс методы не оборачиваю в отдельный модуль. Но вот `include` доступен, возможно в предыдущих версиях Ruby было иначе.

2016-11-15 23:11 UTC, psylone commented on Lesson3/modules/instance_counter.rb
> +    :instances=
Что именно путает?

В первом случае методы после `private` становятся закрытыми. Во втором мы явно определяем закрытый метод: `private :instances=`.

2016-11-15 23:16 UTC, psylone requested changes

2016-11-15 23:16 UTC, psylone commented on Lesson3/modules/instance_counter.rb
> +      #self.class.instances ||= 0
Я думаю это как раз тот случай когда нужно объявить только `attr_reader` а метод сеттер написать самостоятельно и сделать его `private`.

2016-11-15 23:16 UTC, psylone commented on Lesson3/models/train.rb
> +    @@trains.detect { |train| train.number == number }
Вот тут сама идея касалось типа переменной. Давай этот момент проработаем. почему ты используешь **переменную класса**, вместо **переменной экземпляра уровня класса**?

2016-11-16 00:28 UTC, dx0x58 commented on Lesson3/modules/instance_counter.rb
> +    base.send :include, InstanceMethods
Кажется в новых версиях Ruby include больше не private, то есть работает так
def self.included(base)
 base.extend ClassMethods
 base.include InstanceMethods
end
ruby-2.0.0 > Class.private_methods.include? :include # => true
ruby-2.3.1> Class.private_methods.include? :include # => false

2016-11-16 06:49 UTC, evg-tray commented on Lesson3/models/wagon.rb
> +    @train.nil? && self.class.to_s == type
Вот здесь ругается на неинициализированную константу, если написать TYPE_WAGON = Wagon

``` ruby
class Train
  TYPE_WAGON = "Wagon"
```

Вызов:

``` ruby
def attach_wagon(wagon)
  if stopped? && wagon.can_be_attached?(self.class::TYPE_WAGON)
```

2016-11-16 06:56 UTC, evg-tray commented on Lesson3/models/train.rb
> +    @@trains.detect { |train| train.number == number }
Чтобы в этой переменной хранился весь список поездов всех типов, если сделать переменную экземпляра уровня класса, то у базового класса будет свой список, у каждого подчиненного свой. Можно в подчиненных класса добавить условие для фильтра типа поезда
```ruby
@@trains.detect { |train| train.number == number && train.class == self }
```

2016-11-16 18:00 UTC, psylone commented on Lesson3/models/wagon.rb
> +    @train.nil? && self.class.to_s == type
Это понятно, зависит от того в каком порядке всё подключается. Добавь здесь `require_relative wagon` (`require` подключит файл только один раз даже если вызван два раза).

2016-11-16 18:01 UTC, psylone commented on Lesson3/modules/instance_counter.rb
> +    base.send :include, InstanceMethods
Спасибо, @dx0x58

2016-11-16 18:03 UTC, psylone commented on Lesson3/models/train.rb
> +    @@trains.detect { |train| train.number == number }
Это один из вариантов. Или добавить тип в `@@trains`:

```ruby
@@trains = {
  passenger: [],
  cargo: []
}
```

Хотя на самом деле я не думаю что мы захотим напрямую создавать экземпляры базового класса `Train`.

2016-11-16 18:46 UTC, evg-tray commented on Lesson3/models/train.rb
> +    @@trains.detect { |train| train.number == number }
Типы поездов реализованы дочерними классами, думаю излишне добавлять еще типы, характеризующие теже самые типы. В случае добавления нового типа нужно будет править класс `Train`, а так достаточно просто создать унаследованный от него класс.

2016-11-17 10:08 UTC, psylone commented on Lesson3/models/train.rb
> +    @@trains.detect { |train| train.number == number }
Это был просто пример структуры данных. В качестве ключа может использоваться дочерний класс поезда.

2016-11-17 10:34 UTC, psylone commented on Lesson3/models/train.rb
> +    @@trains.detect { |train| train.number == number && (self == Train || train.class == self) }
Предположение о том что мы можем держать экземпляры класса `Train` сводят на нет идею о дочерних классах и наследовании в данном случае. Это всё равно что сделать `Object.new` и сказать что у нас есть объект. Есть, но что он отражает, какую сущность реального мира моделирует не ясно.

2016-11-17 10:34 UTC, psylone commented on Lesson3/modules/instance_counter.rb
>    module ClassMethods
Там ниже идёт определение метода `instances=`. По факту мы ничего не присваиваем, поэтому его можно назвать `register_instance!` или `increment_instances`.

2016-11-17 10:34 UTC, psylone commented on Lesson3/models/train.rb
> +  private :wagons=
Смущает меня всё же этот метод. Если мы не предполагаем его вызов за пределами области видимости объекта, зачем вообще его добавлять в аксессор?

2016-11-17 10:34 UTC, psylone commented on Lesson3/models/train.rb
> +    @@trains << self
Можно в конструкторе вызвать `raise`.

2016-11-17 10:35 UTC, psylone approved these changes

2016-11-17 16:19 UTC, merged